name: Github Actions
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Naga Konada
      - name: Log Greeting Time
        run: echo "${{steps.greet.time}}"